# Generated by Django 4.1.3 on 2022-11-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='posts', to='rareserverapi.member')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='posts', to='rareserverapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='subscription_authors', to='rareserverapi.member')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='subscription_followers', to='rareserverapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_tag_posts', to='rareserverapi.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_tag_tags', to='rareserverapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_react_users', to='rareserverapi.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_react_posts', to='rareserverapi.post')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_react_reactions', to='rareserverapi.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(
                through='rareserverapi.PostReaction', to='rareserverapi.reaction'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(
                through='rareserverapi.PostTag', to='rareserverapi.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('created', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='comment_authors', to='rareserverapi.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='comment_posts', to='rareserverapi.post')),
            ],
        ),
    ]
